substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'OXY' active
   description        'Dissolved Oxygen'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5' active
   description        'carbonaceous BOD (first pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'COD_Cr' active
   description        'COD concentration by the Cr-method'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'IM1' active
   description        'inorganic matter (IM1)'
   concentration-unit '(gDM/m3)'
   waste-load-unit    '-'
end-substance
substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'NO3' active
   description        'Nitrate (NO3)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'PO4' active
   description        'Ortho-Phosphate (PO4)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'POC1' active
   description        'POC1 (fast decomposing fraction)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'PON1' active
   description        'PON1 (fast decomposing fraction)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'POP1' active
   description        'POP1 (fast decomposing fraction)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'Green' active
   description        'Algae (non-Diatoms)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'FColi' active
   description        'Faecal coli bacteria'
   concentration-unit '(MPN/m3)'
   waste-load-unit    '-'
end-substance
substance 'SOD' inactive
   description        'Sediment oxygen demand (SOD)'
   concentration-unit '(gO2/m2)'
   waste-load-unit    '-'
end-substance
substance 'IM1S1' inactive
   description        'IM1 in layer S1'
   concentration-unit '(gDM/m2)'
   waste-load-unit    '-'
end-substance
substance 'DetCS1' inactive
   description        'DetC in layer S1'
   concentration-unit '(gC/m2)'
   waste-load-unit    '-'
end-substance
substance 'DetNS1' inactive
   description        'DetN in layer S1'
   concentration-unit '(gN/m2)'
   waste-load-unit    '-'
end-substance
substance 'DetPS1' inactive
   description        'DetP in layer S1'
   concentration-unit '(gP/m2)'
   waste-load-unit    '-'
end-substance
parameter 'Temp'
   description   'ambient water temperature'
   unit          '(oC)'
   value          0.1500E+02
end-parameter
parameter 'VWind'
   description   'wind speed'
   unit          '(m/s)'
   value          0.3000E+01
end-parameter
parameter 'SWRear'
   description   'switch for oxygen reaeration formulation (1-13)'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SwOXYDem'
   description   'switch oxygen consumption(0=BOD, 1=COD, 2=both)'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'RcBOD'
   description   'decay rate BOD (first pool) at 20 oC'
   unit          '(1/d)'
   value          0.3000E+00
end-parameter
parameter 'RcCOD'
   description   'decay rate COD at 20 oC'
   unit          '(1/d)'
   value          0.5000E-01
end-parameter
parameter 'TcBOD'
   description   'temperature coefficient decay BOD'
   unit          '(-)'
   value          0.1040E+01
end-parameter
parameter 'RcSOD'
   description   'decay rate SOD at 20 oC'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
parameter 'TcSOD'
   description   'temperature coefficient decay SOD'
   unit          '(-)'
   value          0.1040E+01
end-parameter
parameter 'PPMaxGreen'
   description   'maximum production rate Greens'
   unit          '(1/d)'
   value          0.1800E+01
end-parameter
parameter 'MRespGreen'
   description   'maintenance respiration Greens st.temp'
   unit          '(-)'
   value          0.4500E-01
end-parameter
parameter 'GRespGreen'
   description   'growth respiration factor Greens'
   unit          '(-)'
   value          0.1500E+00
end-parameter
parameter 'Mort0Green'
   description   'mortality rate constant Greens'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'MortSGreen'
   description   'mortality rate Greens at high salinity'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'SalM1Green'
   description   'lower salinity limit for mortality Greens'
   unit          '(g/kg)'
   value         -0.9990E+03
end-parameter
parameter 'SalM2Green'
   description   'upper salinity limit for mortality Greens'
   unit          '(g/kg)'
   value         -0.9990E+03
end-parameter
parameter 'Si'
   description   'dissolved Silica (Si)'
   unit          '(gSi/m3)'
   value          0.0000E+00
end-parameter
parameter 'Diat'
   description   'Diatoms'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'VSedBOD5'
   description   'sedimentation velocity CBOD5'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'Tau'
   description   'total bottom shear stress'
   unit          '(N/m2)'
   value         -0.9990E+03
end-parameter
parameter 'TaucSBOD'
   description   'critical shear stress for sedimentation BOD'
   unit          '(N/m2)'
   value          0.1000E+13
end-parameter
parameter 'VSedIM1'
   description   'sedimentation velocity IM1'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TaucSIM1'
   description   'critical shear stress for sedimentation IM1'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'VSedPOC1'
   description   'sedimentation velocity POC1'
   unit          '(m/d)'
   value          0.5000E+00
end-parameter
parameter 'VxSedGreen'
   description   'sedimentation velocity Greens'
   unit          '(m/s)'
   value          0.0000E+00
end-parameter
parameter 'VxSedDiat'
   description   'sedimentation velocity Diatoms'
   unit          '(m/s)'
   value          0.0000E+00
end-parameter
parameter 'VSedGreen'
   description   'sedimentation velocity Greens'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'RcMrtFColi'
   description   'first-order mortality rate FColi'
   unit          '(1/d)'
   value          0.8000E+00
end-parameter
parameter 'TcMrtFColi'
   description   'temperature coefficient for mortality FColi'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'CFRAD'
   description   'conversion factor RAD to mortality rate'
   unit          '(m2/W/d)'
   value          0.8600E-01
end-parameter
parameter 'FrUvVL'
   description   'fraction UV light in visible light'
   unit          '(-)'
   value          0.1200E+00
end-parameter
parameter 'RadSurf'
   description   'irradiation at the water surface'
   unit          '(W/m2)'
   value         -0.9990E+03
end-parameter
output 'Temp'
   description   'ambient water temperature'
end-output
output 'Salinity'
   description   'Salinity'
end-output
output 'Velocity'
   description   'horizontal flow velocity'
end-output
output 'VWind'
   description   'wind speed'
end-output
output 'RCREAR'
   description   'rate constant for reaeration'
end-output
output 'SatPercOXY'
   description   'Actual saturation percentage O2'
end-output
output 'BOD5'
   description   'BOD5'
end-output
output 'COD'
   description   'Chemical oxygen demand COD'
end-output
output 'BOD5-POC'
   description   'contribution of POC to BOD5'
end-output
output 'BODu-POC'
   description   'contribution of POC to calculated BODu'
end-output
output 'BOD5-Phyt'
   description   'contribution of phytoplankton to BOD5'
end-output
output 'BODu-Phyt'
   description   'contribution of Phyt to calculated BODu'
end-output
output 'LimDLGreen'
   description   'daylength limitation function for Greens <0-1>'
end-output
output 'LimNutGree'
   description   'nutrient limitation function Greens <0-1>'
end-output
output 'LimRadGree'
   description   'radiation limitation function Greens <0-1>'
end-output
output 'TFGroGreen'
   description   'temperature function growth Greens <0-1>'
end-output
output 'TFMrtGreen'
   description   'temperature function mortality Greens <0-1>'
end-output
output 'fPPDiat'
   description   'net primary production of Diatoms'
end-output
output 'RcGroDiat'
   description   'primary production rate (minus respiration)Diatoms'
end-output
output 'RcRespDiat'
   description   'respiration rate Diatoms'
end-output
output 'DayL'
   description   'daylength <0-1>'
end-output
output 'fSedBOD5'
   description   'sedimentation flux CBOD5'
end-output
output 'SS'
   description   'suspended solids'
end-output
output 'TIM'
   description   'total inorganic matter'
end-output
output 'TotN'
   description   'total nitrogen (including algae)'
end-output
output 'KjelN'
   description   'Kjeldahl nitrogen'
end-output
output 'DIN'
   description   'dissolved inorganic nitrogen'
end-output
output 'TON'
   description   'total organic N (including algae)'
end-output
output 'PON'
   description   'Particulate Organic Nitrogen (including algae)'
end-output
output 'TotP'
   description   'total phosphorus (including algae)'
end-output
output 'TOP'
   description   'total organic P (including algae)'
end-output
output 'POP'
   description   'particulate organic P (incl algae)'
end-output
output 'fSedIM1'
   description   'sedimentation flux IM1 towards S1'
end-output
output 'fResS1IM1'
   description   'resuspension flux IM1 from layer S1'
end-output
output 'ExtVl'
   description   'total extinction coefficient visible light'
end-output
output 'SecchiDept'
   description   'Secchi depth'
end-output
output 'fMrtDiat'
   description   'mortality flux Diatoms'
end-output
output 'fSedGreen'
   description   'sedimentation flux Greens'
end-output
output 'fSedDiat'
   description   'sedimentation flux Diatoms'
end-output
output 'Cl'
   description   'Chloride'
end-output
output 'Rad_uv'
   description   'UV-irradiation at the segment upper-boundary'
end-output
output 'ExtUv'
   description   'total extinction coefficient UV light'
end-output
output 'RadBot_uv'
   description   'UV-irradiation at the segment lower-boundary'
end-output
active-processes
   name  'NutUpt_Alg' 'Uptake of nutrients by growth of algae'
   name  'DenWat_NO3' 'Denitrification in water column'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'RearOXY' 'Reaeration of oxygen'
   name  'BMS1_DetC' 'Mineralisation detritus carbon in sediment S1'
   name  'BODCOD' 'Mineralisation BOD and COD'
   name  'SedOXYDem' 'Sediment oxygen demand'
   name  'GroMrt_Gre' 'Nett primary production and mortality green algae'
   name  'PPrLim' 'Limitation (numerical) on primary production'
   name  'OXYMin' 'Potential mimimum dissolved oxygen concentration'
   name  'CONSELAC' 'Consumption oxygen/other electron acceptors'
   name  'PosOXY' 'Positive oxygen concentration'
   name  'S_CBOD51' 'Sedimentation CBOD5 (first pool)'
   name  'SED_SOD' 'Sedimentation of oxygen demand'
   name  'Compos' 'Composition'
   name  'Sed_IM1' 'Sedimentation IM1'
   name  'S12TraIM1' 'Resuspension, transport in S1-S2 IM1'
   name  'Secchi' 'Secchi depth for visible-light (370-680nm)'
   name  'S1_Comp' 'Composition sediment layer S1'
   name  'BMS1_DetN' 'Mineralisation detritus nitrogen in sediment S1'
   name  'DecFast' 'Mineralization fast decomp. detritus POC1'
   name  'NutRel_Alg' 'Release (nutrients/detritus) by of mortality algae'
   name  'DenSed_NO3' 'Denitrification in sediment'
   name  'BMS1_DetP' 'Mineralisation detritus phosphorus in sediment S1'
   name  'Sed_POC1' 'Sedimentation POC1 3d'
   name  'S12TraDetC' 'Resuspension, transport in S1-S2 DetC'
   name  'SedNPOC1' 'Sedim. nutrients in POC1'
   name  'S12TraDetN' 'Resuspension, transport in S1-S2 DetN'
   name  'S12TraDetP' 'Resuspension, transport in S1-S2 DetP'
   name  'SedPhDyn' 'Sum sedimentation of algae - Dynamo'
   name  'Sed_Gre' 'Sedimentation green algae'
   name  'FColiMrt' 'Mortality FColi bacteria'
   name  'Salinchlor' 'Conversion of salinity into chloride or vv'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'Veloc' 'Horizontal flow velocity'
   name  'SaturOXY' 'Saturation concentration oxygen'
   name  'TotDepth' 'depth water column'
   name  'Phy_dyn' 'Computation of phytoplankton - Dynamo'
   name  'DL_Green' 'Daylength function for green algae'
   name  'NLGreen' 'Nutrient limiation function for green algae'
   name  'Rad_Green' 'Light efficiency function green algae'
   name  'TF_Green' 'Temperature functions for green algae'
   name  'Daylength' 'Daylength calculation'
   name  'Res_DM' 'Resuspension total bottom material (dry mass)'
   name  'Extinc_VLG' 'Extinction of visible-light (370-680nm) DLWQ-G'
   name  'CalcRadUV' 'UV-Radiation at segment upper and lower boundaries'
   name  'Extinc_UVG' 'Extinction of ultraviolet-light (350-480nm) DLWQ-G'
   name  'CalcRad' 'Radiation at segment upper and lower boundaries'
end-active-processes
